// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQMiUbXlWMJ4tHLBJvfmMJbmncFET4Da8',
    appId: '1:1058840894713:web:6fd871c86b2e3f3c541628',
    messagingSenderId: '1058840894713',
    projectId: 'student-marketplace-fcf80',
    authDomain: 'student-marketplace-fcf80.firebaseapp.com',
    storageBucket: 'student-marketplace-fcf80.firebasestorage.app',
    measurementId: 'G-Z4J7V9MTZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7zpeivBDxRr08IfTiBGVzGNHAD0ItnDE',
    appId: '1:1058840894713:android:ef041b3a4f524dc7541628',
    messagingSenderId: '1058840894713',
    projectId: 'student-marketplace-fcf80',
    storageBucket: 'student-marketplace-fcf80.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfuyBzH2N5uI_f6splvCIeC5cg6sHeaF8',
    appId: '1:1058840894713:ios:ae451031be4033d3541628',
    messagingSenderId: '1058840894713',
    projectId: 'student-marketplace-fcf80',
    storageBucket: 'student-marketplace-fcf80.firebasestorage.app',
    iosBundleId: 'com.example.studentMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQMiUbXlWMJ4tHLBJvfmMJbmncFET4Da8',
    appId: '1:1058840894713:web:735f4e4cbbf24665541628',
    messagingSenderId: '1058840894713',
    projectId: 'student-marketplace-fcf80',
    authDomain: 'student-marketplace-fcf80.firebaseapp.com',
    storageBucket: 'student-marketplace-fcf80.firebasestorage.app',
    measurementId: 'G-MFBKPYZ6B9',
  );
}
