// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOnjOuhwNuTxFqLqBgpacn3kwwvxpyEkk',
    appId: '1:1021889952427:web:a58716e7bc381e9cd415ee',
    messagingSenderId: '1021889952427',
    projectId: 'student-mart-c6f77',
    authDomain: 'student-mart-c6f77.firebaseapp.com',
    storageBucket: 'student-mart-c6f77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU83ZL6vsxFtc_2V1Y4bai6HDkJFU75G0',
    appId: '1:1021889952427:android:394d88d079669b8ad415ee',
    messagingSenderId: '1021889952427',
    projectId: 'student-mart-c6f77',
    storageBucket: 'student-mart-c6f77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPq_JiqlxZxWq_JrhWEpFIYMq1uapPV8',
    appId: '1:1021889952427:ios:a737a86efbd3d2e1d415ee',
    messagingSenderId: '1021889952427',
    projectId: 'student-mart-c6f77',
    storageBucket: 'student-mart-c6f77.firebasestorage.app',
    iosBundleId: 'com.example.studentMarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwPq_JiqlxZxWq_JrhWEpFIYMq1uapPV8',
    appId: '1:1021889952427:ios:a737a86efbd3d2e1d415ee',
    messagingSenderId: '1021889952427',
    projectId: 'student-mart-c6f77',
    storageBucket: 'student-mart-c6f77.firebasestorage.app',
    iosBundleId: 'com.example.studentMarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOnjOuhwNuTxFqLqBgpacn3kwwvxpyEkk',
    appId: '1:1021889952427:web:1efae92e2d4ba87fd415ee',
    messagingSenderId: '1021889952427',
    projectId: 'student-mart-c6f77',
    authDomain: 'student-mart-c6f77.firebaseapp.com',
    storageBucket: 'student-mart-c6f77.firebasestorage.app',
  );
}
